name: rubin55.org
title: false

markdown: GFM
paginate: 3
paginate_path: /:num/
permalink: /:title/
date_format: "%b %-d, %Y"


remote_theme: pages-themes/minimal@v0.2.0

plugins:
- jekyll-remote-theme
